### ISSUE TITLE
Proposing Meetup on 6 April

### ISSUE THREAD

**Issue by craigbox** [kubernetes-barcelona/speakers#1]
* **Title**:  Kubernetes 1.6: what's new
* **Speaker**: Craig Box, Google Cloud
* **Language**: en
* **Type**: Presentation, 45 mins
* **Level**: standard
* **Tags**: 

**Description**

In this talk, Craig will take a look at the newly-released Kubernetes 1.6 and explore a few new features such as:

* autoscaling with custom metrics 
* custom schedulers 
* RBAC 
* The Kubernetes CRI

**Speaker Bio** 

Craig Box is a Kubernetes advocate for Google Cloud, based in London.  His role at Google is spreading the message of our platforms, collecting customer feedback on rough edges, and then bugging the engineers until they are smoothed! He started his career as a systems administrator, and has worked in development, deployment, DevOps, consulting, advisory and management roles.

**Comment by dkapanidis** [comment]
[Done](https://www.meetup.com/Kubernetes-Barcelona/events/238798277/)
