### ISSUE TITLE
Introducing KUDO - Kubernetes operators the easy way

### ISSUE THREAD

**Issue by yankcrime** [kubernetes-barcelona/speakers#10]
* **Title**:  Introducing KUDO, Kubernetes operators the easy way
* **Speaker**:  Nick Jones @yankcrime
* **Language**: en
* **Type**: Presentation 30-45 mins
* **Level**: Standard to advanced
* **Tags**: operators, stateful, lifecycle, live-demo

**Description**
Kubernetes Operators are the next phase of the journey towards automating complex applications in containers. The Kudo project introduces an easy way to build Kubernetes operators using declarative YAML. Many Operators that exist today handle initial deployment, but they don’t provide automation for tasks like binary upgrades, configuration updates, and failure recovery. Implementing a production-grade controller for a complex workload typically requires thousands of lines of code and many months of development. As a result, the quality of operators that are available today varies. The Kudo project provides a universal operator to enable automated creation of operators for Kubernetes, in most cases just using YAML. In this talk, I’ll introduce the Kudo project, and demo the creation of a Kubernetes operator using Kudo.

**Speaker Bio** (optional)
Nick is an experienced I.T {sysadmin, engineer, architect} with a career spanning nearly two decades across a wide variety of industries and sectors. Passionate about new technologies and methodologies, especially those in relation to Open Source, virtualization, orchestration, automation, and all forms of cloud computing. Simultaneously romantic about the old with a penchant for decrepit Sun and SGI kit. Likes Emacs and vi.

**Comment by yankcrime** [comment]
Ping @spiddy - would love to come along to the Kubernetes Barcelona meetup to talk about the above.

**Comment by dkapanidis** [comment]
That would be great! let me check the planning for next events and I'll ping you

**Comment by yankcrime** [comment]
Thanks @spiddy 🙏

**Comment by dkapanidis** [comment]
Hi @yankcrime, we're planning an event on 14th of November. Can you confirm if you can present that date?

**Comment by yankcrime** [comment]
Hi @spiddy.  Unfortunately not, it'll have to be in the New Year for me now - February or March sometime could work.
