### ISSUE TITLE
OPA! Implementing compliance with Open Policy Agent

### ISSUE THREAD

**Issue by Symbianx** [kubernetes-barcelona/speakers#12]
* **Title**: OPA! Implementing compliance with Open Policy Agent
* **Speaker**: Miguel Alexandre
* **Language**: en
* **Type**: Lightning Talk 15 mins
* **Level**: standard
* **Tags**: devops, compliance, opa

**Description**

Making sure every tenant of your cluster is employing best-practices while deploying their application is not an easy task, especially when they are using kubernetes for the first time.

In this lightning talk I will give an introduction to Open Policy Agent and how it can help administrators maintain compliance on their kubernetes clusters. I will go through some real-world use cases and how employing policies can save you from future headaches and teach your users best-practices.

**Speaker Bio** (optional)

Miguel works as a DevOps Engineer at Bynder, where he advocates for best-practices on new technology while also improving and modernizing old stacks. Started as a software engineer and the transition to a DevOps role happened naturally. Container orchestration has been a passion since first playing with it 3 years ago.

**Comment by dkapanidis** [comment]
great 👍 you're on, I'll publish the talk on the meetup.

**Comment by dkapanidis** [comment]
Event is published here: https://www.meetup.com/Kubernetes-Barcelona/events/265833064/

I will announce during this evening, please take a minute to review the information and notify me if you notice something that needs to be updated.
