### ISSUE TITLE
One year of kubernetes in production, lessons learned.

### ISSUE THREAD

**Issue by Fsero** [kubernetes-barcelona/speakers#2]
* **Title**: One year of kubernetes in production, lessons learned.
* **Speaker**: Fabian Selles Rosa
* **Language**: (en | es) I don't mind
* **Type**: (Presentation 30-45 mins | Lightning Talk 5-10 mins) Lightning talk of 10 mins.
* **Level**: (basic | standard | advanced) standard
* **Tags**: (e.g. monitoring, devops, live-coding, workshop)
devops, tips, experiences
**Description**

*Provide a small paragraph that describes your proposal*

Just a brief recap over our experiences maintaining a 30 nodes cluster with different workloads and tenants. I will cover QoS policies, dev vs pro workloads, live migrations struggle, some production issue and maybe other topics.

**Speaker Bio** (optional)

*A short bio of the speaker*
System Engineer at Schibsted. I work on a team who had managed Mesos clusters for 2 years in production, we had added Kubernetes clusters into the mix lately.

**Comment by dkapanidis** [comment]
We've moved to meetup date to 21st of March, can you confirm your availability?

**Comment by Fsero** [comment]
Hi @spiddy sadly i have a business trip on those dates, so i will not be able to make it this time, i would gladly do my talk over the next meetup.

I'm really sorry for this but it was unexpected for me.

**Comment by dkapanidis** [comment]
ok, how about we reschedule it for april's meetup. The date is fixed for Tuesday 24th.

**Comment by dkapanidis** [comment]
Can you confirm your avail for 24th of abril so I can publish the talk?

**Comment by Fsero** [comment]
Hi, i can confirm availability :) sorry for the late notice

**Comment by dkapanidis** [comment]
hi, saw you've seen the cancelation notice. We didn't have sufficient speakers confirmed for the date so we had to postpone. I have tentative dates for next month, I'll notify you very soon to check if you can attend next month

**Comment by dkapanidis** [comment]
Hi our next meetup is planned for 16th of May, can you attend to the meetup to give the lightning talk?

**Comment by Fsero** [comment]
yes!
