### ISSUE TITLE
Sail in the Cloud - An Introduction to Istio

### ISSUE THREAD

**Issue by lordofthejars** [kubernetes-barcelona/speakers#3]
* **Title**:  Sail in the Cloud - An Introduction to Istio
* **Speaker**:  Alex Soto
* **Language**:  en
* **Type**: Presentation 30-45 mins
* **Level**: standard/advanced
* **Tags**: devops, testing-in-production, live-coding

**Description**

Microservices architecture has changed how companies develop and deploy applications. This change has affected testing process as well. New techniques have emerged and others have been enhanced. Does your organization wish to achieve unicorn like speed? With N deploys per day? Or a lead time (time to business value from idea to production) measured in days/weeks instead of months/years? In this session, we will not only describe how to use Istio and Kubernetes but actively demonstrate 3 specific techniques that you can use immediately following the session.

*Provide a small paragraph that describes your proposal*

Currently, Istio is gaining a lot of traction as service-mesh implementation for Kubernetes. In this session, we are going to explore how to install Istio, and how to use it to release new versions of our services correctly.

**Speaker Bio** (optional)

Alex is a software engineer at Red Hat in Developers group. He is a passionate about Java world, software automation and he believes in the open source software model.

Alex is the co-author of Testing Java Microservices book for Manning and contributor of several open source projects such as Arquillian ecosystem or Asciidoctor. He is an international speaker presenting his talks at software conferences like Devoxx, JavaOne, JavaZone or JavaLand.

*A short bio of the speaker*

Alex is a software engineer at Red Hat in Developers group. He is a passionate about Java world, software automation and he believes in the open source software model.

**Comment by dkapanidis** [comment]
description updated: https://www.meetup.com/Kubernetes-Barcelona/events/250572122/
