### ISSUE TITLE
Production Grade K8s Clusters on AWS with Kops

### ISSUE THREAD

**Issue by lkysow** [kubernetes-barcelona/speakers#4]
* **Title**: Production Grade K8s Clusters on AWS with Kops
* **Speaker**: Luke Kysow
* **Language**: en
* **Type**: Presentation 30-45 mins
* **Level**: standard/advanced
* **Tags**: devops, aws

**Description**
In this talk, we'll live-demo bringing up a new production grade Kubernetes cluster in AWS. To do this, we'll use a tool called [kops](https://github.com/kubernetes/kops). We'll cover how kops works and why I recommend using it (at least until [EKS](https://aws.amazon.com/eks/) is generally available). We'll also talk about what makes a cluster production grade and how to integrate a new Kubernetes cluster with your existing infrastructure. This will be a DevOps focused talk and we'll dig into AWS networking, Terraform, and how to manage your core Kubernetes manifests.

**Speaker Bio**
Luke is a software engineer who started out in frontend and slowly got pulled down the stack until he could no longer see out from behind mountains of bash scripts and YAML files. He works now as a Kubernetes consultant and maintainer of [Atlantis](https://github.com/runatlantis/atlantis), an open source tool that helps teams automate their Terraform workflows. He is from Vancouver, Canada and is living in Barcelona for a month.

**Comment by dkapanidis** [comment]
great, can you confirm your availability for 16 may?

**Comment by lkysow** [comment]
@spiddy confirmed

**Comment by dkapanidis** [comment]
description updated: https://www.meetup.com/Kubernetes-Barcelona/events/250572122/

**Comment by dkapanidis** [comment]
@lordofthejars asks if you can swap slots between the two talks

@lkysow  is 20:00 ok for you to do the talk?

**Comment by lkysow** [comment]
Yep!

**Comment by lordofthejars** [comment]
Thanks mate :)

**Comment by lkysow** [comment]
No worries! @spiddy did you want to update the meetup description too? It still has me at 19:15.

**Comment by dkapanidis** [comment]
done!
