### ISSUE TITLE
Reusability in Kubernetes: Developing Helm Charts

### ISSUE THREAD

**Issue by jstriebel** [kubernetes-barcelona/speakers#5]
* **Title**: Reusability in Kubernetes: Developing Helm Charts
* **Speaker**: Jonathan Striebel
* **Language**: en
* **Type**: Presentation 30-45 mins
* **Level**: advanced
* **Tags**: devops, live-coding, helm, kubernetes, reusability, templating, modularity

**Description**

Large Kubernetes setups quickly become unmaintainable, as every single resource needs to be defined explicitly. Helm is a package manager for Kubernetes resources, and allows you to apply software patterns for reusability and modularity to your resources definitions, including templating & packaging.

**Speaker Bio** (optional)

Jonathan Striebel is an experienced speaker, consultant and software engineer from scalable minds. With his DevOps attitude, he modernizes large industry projects to use scalable and maintainable infrastructure stacks. On this mission, he extracts benefits from technologies like Docker containerization, Kubernetes deployment, and CI pipelines.
Besides developing infrastructure solutions, he also works on machine-learning projects like chatbots and image segmentation.

**Comment by dkapanidis** [comment]
We have a date! 25 of abril, please confirm if you can give the talk then.

**Comment by jstriebel** [comment]
@spiddy Yes, that would fit perfectly :+1: Thanks for asking!

**Comment by dkapanidis** [comment]
https://www.meetup.com/Kubernetes-Barcelona/events/260470361/
