### ISSUE TITLE
Softonic Development Flow

### ISSUE THREAD

**Issue by bvis** [kubernetes-barcelona/speakers#6]
* **Title**: Softonic Development Flow
* **Speaker**: Basilio Vera @basi
* **Language**: es
* **Type**: Lightning Talk 15-20 mins
* **Level**: basic
* **Tags**: CI/CD, devops

**Description**
How we develop in Softonic and move workloads to production
We'll talk about our CI/CD pipeline with use cases, tools, secret management, testing environments, Some numbers will be shared: number of deploys, avg time per deploy, etc. 

**Speaker Bio**

* Basilio Vera (Softonic)
“Padre” tecnológico de Softonic, desde 2003 construyendo y evolucionando nuestro stack tecnológico. También crossfiter actualmente en reparación.

**Comment by dkapanidis** [comment]
We have a date! 25 of abril, please confirm if you can give the talk then.

**Comment by bvis** [comment]
👍

**Comment by dkapanidis** [comment]
Meetup updated with info https://www.meetup.com/Kubernetes-Barcelona/events/260470361/
